---
- name: Upload {{ hive_dist_file }}
  copy:
    src: "files/{{ hive_dist_file }}"
    dest: /tmp

- name: Extract {{ hive_dist_file }}
  unarchive:
    src: "/tmp/{{ hive_dist_file }}"
    dest: "{{ hive_root_dir }}"
    group: root
    owner: root
    remote_src: yes

- name: Create symbolic link to Hive installation
  file:
    src: "{{ hive_root_dir }}/{{ hive_release }}"
    dest: "{{ hive_install_dir }}"
    state: link

- name: Add Hive users
  user:
    name: "{{ hive_user }}"
    group: "{{ hadoop_group }}"

- name: Create directory for pid
  file:
    path: '{{ hive_pid_dir }}'
    state: directory
    group: '{{ hadoop_group }}'
    owner: '{{ hive_user }}'

- name: Create log directory
  file:
    path: '{{ hive_log_dir }}'
    state: directory
    group: '{{ hadoop_group }}'
    owner: '{{ hive_user }}'
