# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Create Kafka service
  run_once: true
  uri:
    url: "{{ ranger_kafka_install_properties.POLICY_MGR_URL }}/service/plugins/services"
    method: POST
    body:
      name: "{{ ranger_kafka_install_properties.REPOSITORY_NAME }}"
      isEnabled: true
      configs:
        username: kafka
        password: kafka
        commonNameForCertificate: "{{ ranger_kafka_service_properties.common_name_certificate }}"
        policy.download.auth.users: kafka
        zookeeper.connect: "{{ kafka_server_properties['zookeeper.connect'] }}"
      type: kafka
    body_format: json
    force_basic_auth: yes
    user: admin
    password: "{{ ranger_admin_password }}"
    headers:
      Content-Type: application/json
    status_code: [200, 400]
    validate_certs: no
  register: reg_kafka
  changed_when: reg_kafka.status == 200

- debug:
    var: reg_kafka
