# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- include_role:
    name: tosit.tdp.utils.ssl_tls
    tasks_from: create_keystore
  vars:
    ansible_fqdn: "{{ ranger_kafka_service_properties.common_name_certificate }}"
    keystore_location: "{{ ranger_kafka_keystore_location }}"
    keystore_password: "{{ ranger_kafka_keystore_password }}"

- include_role:
    name: tosit.tdp.utils.ssl_tls
    tasks_from: create_truststore
  vars:
    truststore_location: "{{ kafka_truststore_location }}"
    truststore_password: "{{ kafka_truststore_password }}"
