---
- name: Upload {{ ranger_hive_dist_file }}
  copy:
    src: "files/{{ ranger_hive_dist_file }}"
    dest: /tmp
  diff: no

- name: Extract {{ ranger_hive_dist_file }}
  unarchive:
    src: "/tmp/{{ ranger_hive_dist_file }}"
    dest: "{{ hive_root_dir }}"
    group: root
    owner: root
    remote_src: yes
    creates: "{{ hive_root_dir }}/{{ ranger_hive_release }}"

- name: Create symbolic link to Ranger installation
  file:
    src: "{{ hive_root_dir }}/{{ ranger_hive_release }}"
    dest: "{{ ranger_hive_install_dir }}"
    state: link
