# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Upload {{ ranger_hive_dist_file }}
  ansible.builtin.copy:
    src: "{{ binaries_local_dir }}/{{ ranger_hive_dist_file }}"
    dest: "{{ binaries_upload_dir }}/{{ ranger_hive_dist_file }}"
    owner: root
    group: root
    mode: "644"
  diff: false

- name: Extract {{ ranger_hive_dist_file }}
  ansible.builtin.unarchive:
    src: "{{ binaries_upload_dir }}/{{ ranger_hive_dist_file }}"
    dest: "{{ hive_root_dir }}"
    owner: root
    group: root
    mode: "755"
    remote_src: true
    creates: "{{ hive_root_dir }}/{{ ranger_hive_release }}"

- name: Ensure right permissions on ranger libs
  ansible.builtin.file:
    path: "{{ hive_root_dir }}/{{ ranger_hive_release }}"
    owner: root
    group: root
    mode: "755"
    recurse: true
    state: directory

- name: Create symbolic link to Ranger installation
  ansible.builtin.file:
    src: "{{ hive_root_dir }}/{{ ranger_hive_release }}"
    dest: "{{ ranger_hive_install_dir }}"
    state: link
