# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Template install.properties
  ansible.builtin.template:
    src: install.properties.j2
    dest: "{{ ranger_knox_install_dir }}/install.properties"
    owner: root
    group: root
    mode: "644"
  no_log: "{{ tdp_no_log is not defined or tdp_no_log }}"

# Ranger installation scripts finds knox at "../knox" to add necessary properties to knox-site.xml, generate the ranger-*.xml
# It can also be configured with COMPONENT_INSTALL_DIR_NAME but we still have to make {{ knox_install_dir }}/conf
# a symbolic link to /etc/knox/conf.knox to get the configurations at the right place
# TODO: find a better way to do this

- name: Backup {{ knox_install_dir }}/conf
  ansible.builtin.command: mv {{ knox_install_dir }}/conf {{ knox_install_dir }}/conf.bk
  args:
    creates: "{{ knox_install_dir }}/conf.bk"

- name: Create symbolic link from conf in {{ knox_install_dir }} to actual Knox config dir
  ansible.builtin.file:
    src: "{{ knox_conf_dir }}"
    dest: "{{ knox_install_dir }}/conf"
    state: link

# We also need to fix the path of the ranger-policymgr-ssl.xml containing the trustore properties in ranger-knox-security.xml
- name: Fix the path of ranger-policymgr-ssl.xml in ranger-knox-security-changes.cfg
  ansible.builtin.lineinfile:
    path: "{{ ranger_knox_install_dir }}/install/conf.templates/enable/ranger-knox-security-changes.cfg"
    regexp: '^ranger.plugin.knox.policy.rest.ssl.config.file\s+([^ ]+) (.*)$'
    line: 'ranger.plugin.knox.policy.rest.ssl.config.file /etc/knox/conf/ranger-policymgr-ssl.xml \2'
    backrefs: true

- name: Enable log4j audit in ranger-hive-audit.xml
  ansible.builtin.blockinfile:
    path: "{{ ranger_knox_install_dir }}/install/conf.templates/enable/ranger-knox-audit-changes.cfg"
    marker: "# {mark} ANSIBLE MANAGED BLOCK : log4j audit logs"
    insertbefore: "^AZURE.ACCOUNTNAME"
    block: |
      xasecure.audit.log4j.is.enabled           %XAAUDIT.LOG4J.IS_ENABLED%          mod create-if-not-exists
      xasecure.audit.destination.log4j          %XAAUDIT.LOG4J.DESTINATION%         mod create-if-not-exists
      xasecure.audit.destination.log4j.logger   %XAAUDIT.LOG4J.DESTINATION.LOGGER%  mod create-if-not-exists

  when: enable_ranger_audit_log4j

- name: Run enable-knox-plugin.sh
  ansible.builtin.shell: |
    export JAVA_HOME={{ java_home }}
    ./enable-knox-plugin.sh
  args:
    chdir: "{{ ranger_knox_install_dir }}"

- name: Set authorization from 'XASecurePDPKnox' to {{ tdpknox_authorization.name }}
  community.general.xml:
    path: "{{ knox_conf_dir }}/topologies/{{ item.key }}.xml"
    xpath: /topology/gateway/provider/name[text()="XASecurePDPKnox"]
    value: "{{ tdpknox_authorization.name }}"
  loop: "{{ gateway_topology | dict2items }}"
  when: tdpknox_authorization.name is defined
