---
- name: Create timestamped configuration directory
  file:
    path: '{{ spark_hs_conf_dir }}.{{ ansible_date_time.epoch }}'
    state: directory
    group: '{{ hadoop_group }}'
    owner: '{{ spark_user }}'

- name: Create symbolic link to timestamped configuration directory
  file:
    src: '{{ spark_hs_conf_dir }}.{{ ansible_date_time.epoch }}'
    dest: '{{ spark_hs_conf_dir }}'
    state: link
    group: '{{ hadoop_group }}'
    owner: '{{ spark_user }}'

- name: Template spark-env.sh
  template:
    src: spark-env.sh.j2
    dest: '{{ spark_hs_conf_dir }}.{{ ansible_date_time.epoch }}/spark-env.sh'

- name: Template spark-defaults.conf
  template:
    src: spark-defaults.conf.j2
    dest: '{{ spark_hs_conf_dir }}.{{ ansible_date_time.epoch }}/spark-defaults.conf'
# 
# - name: Verify if truststore already exists
#   stat:
#     path: '{{ spark_truststore_location }}'
#   register: truststore
#
# - name: Create truststore
#   shell: keytool -keystore {{ spark_truststore_location }} -deststorepass {{ spark_truststore_password }} -alias root_ca -import -file /etc/ssl/certs/root.pem -noprompt
#   when: not truststore.stat.exists

- name: Generate principals and keytabs
  shell: |
    cd /etc/security/keytabs
    kadmin -r {{ realm }} -p {{ kadmin_principal }} -w {{ kadmin_password }} -q "addprinc -randkey spark/{{ ansible_fqdn }}"
    kadmin -r {{ realm }} -p {{ kadmin_principal }} -w {{ kadmin_password }} -q "xst -k spark.service.keytab spark/{{ ansible_fqdn }}@{{ realm }}"
    chown {{ spark_user }}:{{ hadoop_group }} spark.service.keytab

- name: Generate principals and keytabs for spnego
  shell: |
    cd /etc/security/keytabs
    kadmin -r {{ realm }} -p {{ kadmin_principal }} -w {{ kadmin_password }} -q "addprinc -randkey HTTP/{{ ansible_fqdn }}"
    kadmin -r {{ realm }} -p {{ kadmin_principal }} -w {{ kadmin_password }} -q "xst -k spnego.service.keytab HTTP/{{ ansible_fqdn }}@{{ realm }}"
    chown {{ spark_user }}:{{ hadoop_group }} spnego.service.keytab
    chmod 640 spnego.service.keytab

- name: Template Spark History Server service file
  template:
    src: spark-history-server.service.j2
    dest: /usr/lib/systemd/system/spark-history-server.service
