# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Backup configuration
  copy:
    src: '{{ hadoop_nn_conf_dir }}/'
    dest: '{{ hadoop_nn_conf_dir }}.{{ ansible_date_time.epoch }}'
    group: '{{ hadoop_group }}'
    owner: '{{ hdfs_user }}'
    remote_src: yes
  tags:
    - backup

- name: Template hadoop-env.sh
  template:
    src: hadoop-env.sh.j2
    dest: '{{ hadoop_nn_conf_dir }}/hadoop-env.sh'
  vars:
    hadoop_log_dir: "{{ hadoop_hdfs_log_dir }}"
    hadoop_pid_dir: "{{ hadoop_hdfs_pid_dir }}"
    hadoop_conf_dir: "{{ hadoop_nn_conf_dir }}"

- name: Template log4j.properties
  template:
    src: log4j.properties.j2
    dest: '{{ hadoop_nn_conf_dir }}/log4j.properties'
  vars:
    hadoop_log_dir: "{{ hadoop_hdfs_log_dir }}"

- name: Template HDFS ZKFC service file
  template:
    src: hadoop-hdfs-zkfc.service.j2
    dest: /usr/lib/systemd/system/hadoop-hdfs-zkfc.service

- name: Render core-site.xml
  template:
    src: core-site.xml.j2
    dest: '{{ hadoop_nn_conf_dir }}/core-site.xml'

- name: Render hdfs-site.xml
  include_role:
    name: tosit.tdp.utils.template_plus
    tasks_from: render_template
  vars:
    template_plus_src: "hdfs-site.xml.j2"
    template_plus_dest: "{{ hadoop_nn_conf_dir }}/hdfs-site.xml"

- name: Render jmxremote.password
  template:
    src: jmxremote.password.j2
    dest: '{{ hadoop_nn_conf_dir }}/jmxremote.password'
