# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Add directories for yarn and mapred
  run_once: true
  tosit.tdp.hdfs_file:
    hdfs_conf: "{{ hadoop_client_conf_dir }}"
    path: "{{ item.path }}"
    state: "{{ item.state | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    kerberos: true
    krb_principal: "{{ hdfs_headless_principal }}@{{ realm }}"
    krb_keytab: /etc/security/keytabs/hdfs.headless.keytab
  become: true
  become_user: "{{ hdfs_user }}"
  loop:
    - path: /mr-history
      state: directory
      owner: "{{ mapred_user }}"
      group: "{{ hadoop_group }}"
      mode: "777"
    - path: /mr-history/done
      state: directory
      owner: "{{ mapred_user }}"
      group: "{{ hadoop_group }}"
      mode: "777"
    - path: /mr-history/tmp
      state: directory
      owner: "{{ mapred_user }}"
      group: "{{ hadoop_group }}"
      mode: "777"
    - path: /app-logs
      state: directory
      owner: "{{ yarn_user }}"
      group: "{{ hadoop_group }}"
      mode: "777"
    - path: /ranger/audit/yarn
      state: directory
      owner: "{{ yarn_user }}"
      group: "{{ yarn_user }}"
      mode: "700"
    - path: /tmp
      state: directory
      mode: "777"
    - path: /tmp/hadoop-yarn/staging
      state: directory
      owner: "{{ yarn_user }}"
      group: "{{ hadoop_group }}"
      mode: "1777"
    - path: /hbase/coprocessor
      state: directory
      owner: "{{ hbase_user }}"
      group: "{{ hadoop_group }}"
      mode: "775"
    - path: /hbase/coprocessor/hadoop-yarn-server-timelineservice.jar
      state: file
      src: "{{ hadoop_root_dir }}/{{ hadoop_release }}/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-hbase-coprocessor-{{ hadoop_version }}.jar"
      owner: "{{ hbase_user }}"
      group: "{{ hadoop_group }}"
      mode: "775"
