# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
# tdp-cluster
- ansible.builtin.import_playbook: exporter.yml
- ansible.builtin.import_playbook: zookeeper.yml
- ansible.builtin.import_playbook: hadoop.yml
- ansible.builtin.import_playbook: kerberos.yml
- ansible.builtin.import_playbook: ranger.yml
- ansible.builtin.import_playbook: hdfs.yml
- ansible.builtin.import_playbook: spark3.yml
- ansible.builtin.import_playbook: yarn.yml
- ansible.builtin.import_playbook: hbase.yml
- ansible.builtin.import_playbook: hive.yml
- ansible.builtin.import_playbook: knox.yml
