---
- import_playbook: hdfs_datanode_install.yml
- import_playbook: hdfs_datanode_config.yml
- import_playbook: hdfs_journalnode_install.yml
- import_playbook: hdfs_journalnode_config.yml
- import_playbook: hdfs_namenode_install.yml
- import_playbook: hdfs_namenode_config.yml
- import_playbook: yarn_apptimelineserver_install.yml
- import_playbook: yarn_apptimelineserver_config.yml
- import_playbook: yarn_nodemanager_install.yml
- import_playbook: yarn_nodemanager_config.yml
- import_playbook: yarn_resourcemanager_install.yml
- import_playbook: yarn_resourcemanager_config.yml
- import_playbook: hadoop_client_install.yml
- import_playbook: hadoop_client_config.yml
- import_playbook: hadoop_ssl-tls_install.yml
- import_playbook: hadoop_kerberos_install.yml

- import_playbook: hdfs_namenode_formatzk.yml
- import_playbook: hdfs_journalnode_start.yml
- import_playbook: hdfs_namenode_start.yml
- import_playbook: hdfs_datanode_start.yml
- import_playbook: yarn_apptimelineserver_start.yml
- import_playbook: yarn_resourcemanager_start.yml
- import_playbook: yarn_nodemanager_start.yml

- import_playbook: yarn_hdfs_init.yml
