# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Config jmx-exporter for Kafka Broker
  hosts: kafka_broker
  tasks:
    - tosit.tdp.resolve:
        node_name: kafka_jmx-exporter
    - import_role:
        name: tosit.tdp.kafka.broker
        tasks_from: jmx-exporter
    - meta: clear_facts
