# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: jmx-exporter Spark HS config
  hosts: spark4_hs
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: spark4_jmx-exporter
    - name: Configure Spark History Server jmx-exporter
      ansible.builtin.import_role:
        name: tosit.tdp.spark.common
        tasks_from: jmx-exporter
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
