# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Install Spark3 Yarn Shuffle
  hosts: yarn_shufflespark3
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: yarn_shufflespark3
    - name: Install Yarn Shuffle
      ansible.builtin.import_role:
        name: tosit.tdp.yarn.shufflespark3
        tasks_from: install
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
