# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Zookeeper for Kafka Client config
  hosts: zk_kafka_client
  tasks:
    - tosit.tdp.resolve:
        node_name: zookeeperkafka_client
    - import_role:
        name: tosit.tdp.zookeeper.client
        tasks_from: config
    - meta: clear_facts
