# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Zookeeper Server for Kafka config
  hosts: zk_kafka
  tasks:
    - tosit.tdp.resolve:
        node_name: zookeeperkafka_server
    - import_role:
        name: tosit.tdp.zookeeper.server
        tasks_from: config
    - meta: clear_facts
