# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Backup configuration
  copy:
    src: "{{ hbase_rs_conf_dir }}/"
    dest: "{{ hbase_rs_conf_dir }}.{{ ansible_date_time.epoch }}"
    owner: root
    group: root
    mode: "755"
    remote_src: true
  tags:
    - backup

- name: Template hbase-env.sh
  template:
    src: hbase/hbase-env.sh.j2
    dest: "{{ hbase_rs_conf_dir }}/hbase-env.sh"
    owner: root
    group: root
    mode: "644"

- name: Template log4j.properties
  template:
    src: hbase/log4j.properties.j2
    dest: "{{ hbase_rs_conf_dir }}/log4j.properties"
    owner: root
    group: root
    mode: "644"

- name: Render hbase-site.xml
  template:
    src: hbase/hbase-site.xml.j2
    dest: "{{ hbase_rs_conf_dir }}/hbase-site.xml"
    owner: root
    group: root
    mode: "644"

- name: Copy core-site.xml
  copy:
    src: "{{ hadoop_client_conf_dir }}/core-site.xml"
    dest: "{{ hbase_rs_conf_dir }}/core-site.xml"
    owner: root
    group: root
    mode: "644"
    remote_src: true

- name: Copy hdfs-site.xml
  copy:
    src: "{{ hadoop_client_conf_dir }}/hdfs-site.xml"
    dest: "{{ hbase_rs_conf_dir }}/hdfs-site.xml"
    owner: root
    group: root
    mode: "644"
    remote_src: true

- name: Render jmxremote.password
  template:
    src: hbase/jmxremote.password.j2
    dest: "{{ hbase_rs_conf_dir }}/jmxremote.password"
    owner: root
    group: root
    mode: "644"

- name: Run fluentbit configuration
  import_role:
    name: tosit.tdp.utils.fluentbit
    tasks_from: config
