# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Backup configuration
  ansible.builtin.copy:
    src: "{{ hadoop_httpfs_conf_dir }}/"
    dest: "{{ hadoop_httpfs_conf_dir }}.{{ ansible_date_time.epoch }}"
    group: "{{ hadoop_group }}"
    owner: "{{ hdfs_user }}"
    mode: "755"
    remote_src: true
  tags: ['backup', 'never']

- name: Template hadoop-env.sh
  ansible.builtin.template:
    src: hadoop-env.sh.j2
    dest: "{{ hadoop_httpfs_conf_dir }}/hadoop-env.sh"
    owner: root
    group: root
    mode: "644"
  vars:
    hadoop_pid_dir: "{{ hadoop_hdfs_pid_dir }}"
    hadoop_conf_dir: "{{ hadoop_httpfs_conf_dir }}"

- name: Template httpfs-env.sh
  ansible.builtin.template:
    src: httpfs-env.sh.j2
    dest: "{{ hadoop_httpfs_conf_dir }}/httpfs-env.sh"
    owner: root
    group: root
    mode: "644"

- name: Template log4j.properties
  ansible.builtin.template:
    src: log4j.properties.j2
    dest: "{{ hadoop_httpfs_conf_dir }}/log4j.properties"
    owner: root
    group: root
    mode: "644"

- name: Render core-site.xml
  ansible.builtin.template:
    src: core-site.xml.j2
    dest: "{{ hadoop_httpfs_conf_dir }}/core-site.xml"
    owner: root
    group: root
    mode: "644"

- name: Render hdfs-site.xml
  ansible.builtin.template:
    src: hdfs-site.xml.j2
    dest: "{{ hadoop_httpfs_conf_dir }}/hdfs-site.xml"
    owner: root
    group: root
    mode: "644"

- name: Render httpfs-site.xml
  ansible.builtin.template:
    src: httpfs-site.xml.j2
    dest: "{{ hadoop_httpfs_conf_dir }}/httpfs-site.xml"
    owner: root
    group: root
    mode: "644"
